site_name: Mermaid extension for Python-Markdown
site_author: Hideyuki KATO
repo_url: https://github.com/hkato/markdown-mermaid-data-uri
repo_name: hkato/markdown-mermaid-data-uri
copyright: Copyright © 2025 Hideyuki KATO

theme:
  name: material
  features:
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown_mermaid_data_uri:
      mermaid_cli: true

plugins:
  - search
  - to-pdf:
      cover_subtitle: using Kroki / Mermaid-CLI
      download_link: header

nav:
  - Home: index.md
  - Examples: mermaid.md
