site_name: Diagram extension for Python-Markdown
site_author: Hideyuki KATO
repo_url: https://github.com/hkato/markdown-kroki
repo_name: hkato/markdown-kroki
copyright: Copyright © 2025 Hideyuki KATO

theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown_kroki:
      # kroki_url: http://localhost:18000

plugins:
  - search
  - to-pdf:
      cover_subtitle: using Kroki
      download_link: header
