site_name: Mermaid extension for Python-Markdown
site_author: Hideyuki KATO
repo_url: https://github.com/hkato/markdown-mermaid-cli
copyright: Copyright © 2025 Hideyuki KATO

theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown_mermaid_cli

plugins:
  - search
  - to-pdf:
      cover_subtitle: using mermeaid-cli
      download_link: header

nav:
  - Home: index.md
  - Examples: mermaid.md
