[project]
name = "markdown-mermaid-cli"
version = "0.1.0"
description = "markdown-mermaid-cli"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "markdown>=3.8",
]

[tool.ruff]
line-length = 119
[tool.ruff.format]
quote-style = "single"
